services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "db-max-pizze"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - v-max-pizza:/var/lib/postgresql/data

volumes:
  v-max-pizza: